### ISSUE TITLE
Location of template file

### ISSUE THREAD

**Issue by schymane** [jcheminform/markdown-jcheminf#2]
By shifting the article to the templates folder, this "create template" option no longer works out of the box (you would need the filter subfolders within template, and the style files etc in the template folder?) 
... and for RMarkdown the *.Rmd file is missing ...?

(or am I missing something @egonw ?)

**Comment by egonw** [comment]
You need to select one of the templates (for the article type you want to write), as here written in the [README](https://github.com/jcheminform/markdown-jcheminf/blob/master/README.md):

![image](https://user-images.githubusercontent.com/26721/112166747-34d94c00-8bf0-11eb-87cc-cbb32445d0b6.png)

I guess this text could use improvement...

**Comment by egonw** [comment]
(And the rticles package will further simplify this, when that is done...)

**Comment by schymane** [comment]
Well ... in your earlier versions they were already inline and it worked nicely. Now you need manual copying ... seems like a step backwards to me ... because the "Use this template" button is no longer really using this template ... 
(where as before, I clicked on that button, named my repo, cloned, and I was ready to go - article.Rmd worked out of the box!)

![image](https://user-images.githubusercontent.com/4070141/112167558-d5c80700-8bf0-11eb-9353-01568cecadb8.png)

**Comment by egonw** [comment]
Ah, but that button is about a different "template" Though it's easy to see how this is very confusing... that button is for a GitHub repo template, not an article template...

I will update the README to clarify this (after Thursday)

**Comment by schymane** [comment]
I see that it's a different template function ... but it would work as both very easily (I mean, if you are coding ... you'd want a new repo anyway right?)

**Comment by egonw** [comment]
Yes, but then I need one repo for each article type :(

**Comment by schymane** [comment]
Hmm or one with `article.md` and `article.Rmd` in the main folder, and then alternative templates in the `templates` folder?
(so most popular article would work out of the box, and other types can be copied over and we don't have tonnes of files in the main folder?)

Btw keywords are missing from the template ...

**Comment by egonw** [comment]
There is just an `article.Rmd` now. Turns out that works out just fine with the same YAML header.

**Comment by schymane** [comment]
Two quick points (don't want to fiddle not to cause commit conflicts in case you are still working):
* README now links to a 404 (links to research.md not research-article.Rmd) and has a typo (release not research)
(https://github.com/jcheminform/markdown-jcheminf/blob/master/templates/research_article.Rmd)
* Maybe a silly question but do we want `*.md` and `*.Rmd` versions? (is `*.Rmd` sufficiently universal?)

**Comment by egonw** [comment]
Just `.Rmd` seems to do fine.

**Comment by schymane** [comment]
Research article is still a "release" article tho :-( but good that Rmd works universally!
