### ISSUE TITLE
Multiple identical CiTOs

### ISSUE THREAD

**Issue by schymane** [jcheminform/markdown-jcheminf#4]
If we as authors write multiple CiTOs that are the same, they are not filtered in the output, but repeated ...
(which is good behaviour if they are different, but not if they are identical).

So my question is ... do we need an extra filter to remove repetition, or update the documentation to make it clear that you only use each CiTO term once per ref? @egonw @tarleb any thoughts?

![image](https://user-images.githubusercontent.com/4070141/112189344-344ab080-8c04-11eb-9761-9f18517d7b32.png)

![image](https://user-images.githubusercontent.com/4070141/112189451-50e6e880-8c04-11eb-987e-2f27d56ae7d7.png)

**Comment by egonw** [comment]
We (JCheminf) had not discussed this situation yet, but I would argue that the Reference list applies a `DISTINCT` filter :)

**Comment by tarleb** [comment]
I'm starting work on a patch now.

**Comment by egonw** [comment]
Fixed.
